import puppeteer from "puppeteer-core";
const D = "C:/Users/oscar/Desktop/filer till claude/bugg 1";
const browser = await puppeteer.launch({ executablePath: "C:/Program Files/Google/Chrome/Application/chrome.exe", headless: true, args: ["--use-angle=swiftshader", "--enable-unsafe-swiftshader", "--window-size=1500,950"], defaultViewport: { width: 1500, height: 950 } });
const page = await browser.newPage();
const messages = [];
page.on("console", (m) => { if (m.type() === "error" || m.type() === "warning") messages.push(`${m.type()}: ${m.text()}`); });
page.on("pageerror", (e) => messages.push(`pageerror: ${e.message}`));
await page.goto("https://sond-appen.vercel.app/?v=" + Date.now(), { waitUntil: "load" });
const input = await page.$("#file-input");
await input.uploadFile(`${D}/2026-10-07-Hakunge.txt`, `${D}/261007hakunge.dm4`, `${D}/261007hakunge1.dm4`);
await page.waitForFunction(() => [...document.querySelectorAll("#file-status li")].length >= 3, { timeout: 60000 });
await new Promise((r) => setTimeout(r, 2500));
console.log("produktion, filer:", await page.$$eval("#file-status li", (els) => els.map((e) => e.textContent?.trim().slice(0, 40)).join(" | ")));
console.log("hål-panel:", await page.$eval("#unmatched", (el) => el.textContent?.trim()));
console.log("borttagna-panel dold:", await page.$eval("#removed-panel", (el) => el.hidden));
await page.click(`.tabs button[data-tab="plan"]`);
await new Promise((r) => setTimeout(r, 1500));
console.log(JSON.stringify(await page.evaluate(() => ({ holes: document.querySelectorAll("#plan-container g.plan-hole").length, h63: !!document.querySelector('#plan-container g.plan-hole[data-source="63"]'), h37: !!document.querySelector('#plan-container g.plan-hole[data-source="37"]') }))));
console.log("meddelanden:", messages.length ? messages.join("\n") : "inga");
await browser.close();
